### ISSUE TITLE
[FEATURE] Shortcut for focusing search box

### ISSUE THREAD

**Issue by mmoya** [hardpixel/devdocs-desktop#10]
It would be nice to bind `/` or `Ctrl + F` to focusing the search box.

**Comment by jonian** [comment]
Hi.

There is a shortcut to focus the search box, `Esc`, same as in devdocs.io website.

`Ctrl + F` is in use by the finder which is included in the latest commits.

**Comment by jonian** [comment]
I'm closing this since there already is a shortcut to focus the search box.
