### ISSUE TITLE
Application complain about name resolution if opened without connection

### ISSUE THREAD

**Issue by Porkepix** [hardpixel/devdocs-desktop#14]
As visible on the joined screenshot, application complain about being unable to resolve devdocs.io if there's no connection when it's opened (need the connection at launch, fail otherwise).

`Error resolving “devdocs.io”: Temporary failure in name resolution`

![screenshot from 2018-06-03 10-10-25](https://user-images.githubusercontent.com/709500/40884579-7e87ea5c-6716-11e8-99c5-c185aa097d98.png)

**Comment by tocsinde** [comment]
Can confirm. Really frustrating to have saved docs for offline usage and then not be able to read any of them without connection :/

**Comment by jonian** [comment]
Fixed in master branch.

**Comment by LeOSW42** [comment]
Hello,

I just installed that app from AUR (1.0.0) and accessed once with internet access.
Then switched to airplane mode on my laptop, then started the app again and the same issue as mentioned above.

I have an up to date Archlinux install.

Léo
