### ISSUE TITLE
text-decoration dots are not exactly around the checkbox

### ISSUE THREAD

**Issue by Porkepix** [hardpixel/devdocs-desktop#16]
As visible on the joined screenshot, when selecting or unselecting a checkbox in the list of enabled docs, it's surrounded by text-decoration dots, but it doesn't exactly fit around the checkbox: it goes a little more far on the left.

![screenshot from 2018-06-18 02-38-11](https://user-images.githubusercontent.com/709500/41513800-b93d7a5e-72a1-11e8-8836-d442e716f7d1.png)

**Comment by jonian** [comment]
This is an issue of the devdocs.io website rendering in webkit not an application issue.
