### ISSUE TITLE
Offline Support

### ISSUE THREAD

**Issue by cookiengineer** [hardpixel/devdocs-desktop#18]
How would somebody implement offline support?

Currently, a launch still requires an internet connection in order to download the initial html + web worker scripts. Now my question is mostly about the architecture: Is it possible to offer the index files baked into the app itself; so that this is not necessary anymore?

I've seen that that the web application cache is enabled in the [devdocs_desktop.py](https://github.com/hardpixel/devdocs-desktop/blob/master/devdocs_desktop.py#L48) but I'm currently unsure on how to provide a cache.

Do you know whether or not webkitgtk can be integrated with a self-provided cache file for the index.html?

**Comment by jonian** [comment]
This seems to have been an issue with webkit2gtk. Offline mode works with webki2gtk 2.28.1.

**Comment by cookiengineer** [comment]
The `index.html` and request thereof (+ the service worker) are both uncached and need an internet connection to work.

You can verify this by disabling your internet connection before you start devdocs_desktop for the first time. Seemingly after every restart of devdocs desktop, this will be necessary again.

Did it work with your newest webkit2gtk version? I am using `2.28.1-1` on Arch, and the issue seems to persist. How can I verify what's been cached correctly?

**Comment by jonian** [comment]
I tested on Arch too, but not by disabling your internet connection before you start devdocs_desktop for the first time. The same happens with epiphany.

Here are the [webkitgtk docs](https://lazka.github.io/pgi-docs/#WebKit2-4.0), if you want to take a look.

**Comment by jonian** [comment]
@cookiengineer Can you test with master branch? I works for me now. Thanks!
