### ISSUE TITLE
[Enhancement] Open external links in documentation on left click

### ISSUE THREAD

**Issue by persidskiy** [hardpixel/devdocs-desktop#20]
Steps:
1. Open any doc with link inside (e.g. `os.path`)
2. Click on external link
3. Nothing happens

![devdocsbug](https://user-images.githubusercontent.com/1527181/84262390-3389d780-ab26-11ea-97c4-2e1199242157.png)

**Comment by jonian** [comment]
Hi @persidskiy, sorry for the super late response. You can open _external_ links with right click. External links will open in your default browser.
