### ISSUE TITLE
[Feature] CTLR+ENTER to open page in browser

### ISSUE THREAD

**Issue by juliavdkris** [hardpixel/devdocs-desktop#23]
Hi there! First of all, thank you for creating and maintaining this project! It is super useful and I really appreciate your time and effort.

DevDocs has a CTRL+ENTER shortcut to open a page in a new tab. I think it would be great to add this functionality as well. Perhaps by simply opening the page in the user's browser, or if you prefer having everything in the program itself, maybe add some sort of tab functionality?

**Comment by jonian** [comment]
Hi @samvdkris, thanks for the report. Making all DevDocs shortcuts work is a goal of this application. I will work on it as soon as I find some free time.

Since devdocs-desktop does not have support for in-application tabs yet, it will open in the user's browser.

**Comment by juliavdkris** [comment]
@jonian Awesome! Nice to hear that this was already on the list of planned features. And no rush of course, devdocs-desktop is already great as it is. And if I really need multiple tabs I can always just use my browser. I just wanted to suggest this feature in case you hadn't considered it yet :)
